services:
  catalog:
    build: 
      context: PizzaCatalog
      target: final
    container_name: catalog
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      postgres:
        condition: service_healthy

  ordering:
    build: 
      context: PizzaOrdering
      target: final
    container_name: ordering
    ports:
      - 5002:5002
      - 5003:5003
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: on-failure
    container_name: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    environment:
      POSTGRES_MULTIPLE_DATABASES: pizzaCatalog,pizzaOrdering
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: db123
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: